name: "Deploy to GCP"

on:
  push:
    branches:
      - master

env:
  JSON: ${{ secrets.GCP_JSON_CREDENTIAL }}

jobs:
  job_id:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ env.JSON }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v2'
      timeout-minutes: 10
      with:
        name: 'japan-news-scraper'
        runtime: 'python312'

    # Example of using the output
    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.url }}"'